version: '3.7'

services:
 
  # app:
  #   image: some-image
  #   links:
  #     - redis-sentinel

  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - 7843:7843
    depends_on:
      - redis-master
    volumes:
      - ./p3x-redis-ui-settings:/settings
    networks:
      redis-network:
          ipv4_address: 172.16.100.100
 
  redis-master:
    image: redis:7.0.5
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
    env_file:
      - redis-master.env
    command: /bin/sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    networks:
      redis-network:
          ipv4_address: 172.16.100.1 
 
  redis-slave:
    image: redis:7.0.5
    command: /bin/sh -c "redis-server --appendonly yes --slaveof 172.16.100.1 6379 --masterauth $$REDIS_PASSWORD --requirepass $$REDIS_PASSWORD"
    # command: redis-server --slaveof 172.16.100.1 6379
    links:
      - redis-master
    volumes:
      - "./.data-slave:/data"
    env_file:
      - redis-master.env
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      redis-network:
          ipv4_address: 172.16.100.2 

  # Instance 1
  redis-sentinel1:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - "6381:6379"
      - "26381:26379"
    environment:
      - REDIS_MASTER_PASSWORD=redissecret
      - REDIS_SENTINEL_USERNAME=sentineluser
      - REDIS_SENTINEL_PASSWORD=sentienlsecret
    networks:
      redis-network:
          ipv4_address: 172.16.100.3

  # Instance 2
  redis-sentinel2:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - "6382:6379"
      - "26382:26379"
    environment:
      - REDIS_MASTER_PASSWORD=redissecret
      - REDIS_SENTINEL_USERNAME=sentineluser
      - REDIS_SENTINEL_PASSWORD=sentienlsecret
    networks:
      redis-network:
          ipv4_address: 172.16.100.4
 
  # Instance 3
  redis-sentinel3:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - "6383:6379"
      - "26383:26379"
    environment:
      - REDIS_MASTER_PASSWORD=redissecret
      - REDIS_SENTINEL_USERNAME=sentineluser
      - REDIS_SENTINEL_PASSWORD=sentienlsecret
    networks:
      redis-network:
          ipv4_address: 172.16.100.5 

networks:
  redis-network:
    name: custom_redis_network
    # use the bridge driver, but enable IPv6
    driver: bridge
    ipam:
        driver: default
        config:
          - subnet: 172.16.100.0/24
            gateway: 172.16.100.254